// AUTO-GENERATED by server at 2025-09-19T23:35:43.477Z
// Do not edit by hand. Update via the Spec Builder UI.

export type CriteriaType = "MQP" | "Visual";
export type SpecClass = "Critical" | "Major" | "Minor";

export interface QAPSpecification {
  id: string;
  criteria: CriteriaType;
  subCriteria: string;
  specification: string;
  class: SpecClass;
  description?: string;
  sampling?: string;
  typeOfCheck?: string;
}

export const mqpSpecifications: QAPSpecification[] = [

];

export const visualElSpecifications: QAPSpecification[] = [

];

export const qapSpecifications: QAPSpecification[] = [
  ...mqpSpecifications,
  ...visualElSpecifications,
];
